modLoader = "javafml"
loaderVersion = "[4,)"
license = "BSD-3-Clause + CC BY-NC-SA 4.0"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "kaleidoscope_tavern.mixins.json"

[[mods]]
modId = "kaleidoscope_tavern"
version = "1.0.1-neoforge+mc1.21.1"
displayName = "Kaleidoscope Tavern"
authors = "ysbbbbbb, tartaric_acid"
description = '''Focused on tavern-themed content, adding a complete brewing system along with a rich selection of decorative blocks to bring your tavern to life.'''

[[dependencies."kaleidoscope_tavern"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."kaleidoscope_tavern"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"
