
modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

authors="Tequilacat"

description='''
A kaleidoscope extension.
'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kaleidoscope_cookery"
    type="required"
    versionRange="[1.4.1-neoforge+mc1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kaleidoscope_tavern"
    type="required"
    versionRange="[1.0.1-neoforge+mc1.21.1,)"
    ordering="NONE"
    side="BOTH"
